# Generated by Django 3.1.5 on 2021-02-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0004_uploadmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='genre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
